apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-app
  labels:
    app: travel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-app
  template:
    metadata:
      labels:
        app: travel-app
    spec:
      containers:
        - name: travel-app
          image: adityaglobe/traveledmlops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

